var Transform = require('stream').Transform;
var util = require('util');

function ChopStream() {
  this._buff = undefined;
  this._deleting = false;

  Transform.call(this);
}

util.inherits(ChopStream, Transform);

ChopStream.prototype._transform = function(chunk, encoding, done) {
  var start = "## >> Generated by fokus";
  var end = "## <<";

  if (chunk.toString() === start) {
    this._deleting = true;
  } else if (chunk.toString() === end) {
    this._deleting = false;
  } else {
    if (!this._deleting) this.push(chunk + '\n');
  }

  done();
};

ChopStream.prototype._flush = function(done) {
  done();
};

module.exports = new ChopStream();
