var Transform = require('stream').Transform;
var util = require('util');
var strings = require('./strings');

function ChopStream() {
  this._buffer = undefined;
  this._deleting = false;

  Transform.call(this);
}

util.inherits(ChopStream, Transform);

ChopStream.prototype._transform = function(chunk, encoding, done) {
  var start = "## >> Generated by fokus";
  var end = "## <<";
  chunk = chunk.toString();

  if (chunk === start) {
    this._deleting = true;
  } else if (chunk === end) {
    this._deleting = false;
  } else {
    if (!this._deleting) {
      // make sure to append a newline again after split
      this.push(new Buffer(chunk + '\n'));
    }
  }

  done();
};

ChopStream.prototype._flush = function(done) {
  done();
};

module.exports = new ChopStream();
